##
#  This compose file is used for local development and adapter testing only.
#  See `/docker` for a generic and production-ready docker file
##

version: "3.5"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbt"
    ports:
      - "5435:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        USER_ID: ${USER_ID:-}
        GROUP_ID: ${GROUP_ID:-}
    command: "/root/.virtualenvs/dbt/bin/pytest"
    environment:
      POSTGRES_TEST_HOST: "database"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    depends_on:
      - database
